"""update Planet model

Revision ID: 1aeb2d9c2e75
Revises: 121486141f79
Create Date: 2022-12-20 19:52:02.304999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aeb2d9c2e75'
down_revision = '121486141f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('atmosphere', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'atmosphere')
    # ### end Alembic commands ###
