"""adds Planet model

Revision ID: 35df06ad1029
Revises: 
Create Date: 2022-12-20 12:08:30.904434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35df06ad1029'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('orbit_days', sa.Integer(), nullable=True),
    sa.Column('num_moons', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planet')
    # ### end Alembic commands ###
