"""Add Planet model

Revision ID: C1
Revises: 
Create Date: 2022-12-21 20:25:38.347061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'C1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('livable', sa.Boolean(), nullable=True),
    sa.Column('number_of_moons', sa.Integer(), nullable=False),
    sa.Column('length_of_year', sa.Integer(), nullable=False),
    sa.Column('namesake', sa.String(), nullable=False),
    sa.Column('atmosphere', sa.String(), nullable=False),
    sa.Column('diameter', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planet')
    # ### end Alembic commands ###
