"""adds color

Revision ID: c3e5c7fe877e
Revises: 927e0daedb50
Create Date: 2022-12-22 08:39:22.115786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e5c7fe877e'
down_revision = '927e0daedb50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('color', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'color')
    # ### end Alembic commands ###
